services:
  - type: web
    name: fenix-coin-ultra-web
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.10
      - key: DATABASE_URL
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: BOT_USERNAME
        sync: false
      - key: WEBAPP_URL
        sync: false
      - key: ADMIN_IDS
        sync: false

  - type: worker
    name: fenix-coin-ultra-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.10
      - key: DATABASE_URL
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: BOT_USERNAME
        sync: false
      - key: WEBAPP_URL
        sync: false
      - key: ADMIN_IDS
        sync: false
